<<<<<<< HEAD
name: Codeando DF
=======
name: CodeandoDF
>>>>>>> 5ac8ca0689ed94c54a321e31bc4d01cc9654657e
url: http://codeandodf.org
markdown: redcarpet
highlighter: pygments
paginate: 10
paginate_path: "/blog/:num"
gems:
    - jekyll-sitemap
collections:
    resources:
        output: true
