name: Codeando DF
url: http://codeandodf.org
markdown: redcarpet
highlighter: pygments
paginate: 10
paginate_path: "/blog/:num"
gems:
    - jekyll-sitemap
collections:
    resources:
        output: true
